Optimization

2 State HMM

In [1]:
import os
import numpy as np
from hidden import dynamics, infer
# This is only if you want to use non-default optimization routines (global)
from hidden.optimize.base import OptClass

# Initializedynamics
hmm = dynamics.HMM(2, 2)
#hmm=dynamics.HMM(3,3) 
hmm.init_uniform_cycle(0.2, 0.1) 
hmm.A, hmm.B

(array([[0.8, 0.2],
        [0.2, 0.8]]),
 array([[0.9, 0.1],
        [0.1, 0.9]]))

In [2]:
hmm.run_dynamics(250)

In [1]:
#eta diye data automatic save kora jae.
import os
from pathlib import Path
proj_dir= Path().resolve().parents[1]
#proj_dir= Path().resolve().parents[] first e eta diye dekhbo amra koi asi, ekhane amar data ta hmm er under e . first path 

#theke amar hmm path porjonto koto tuku 0,1,ebhabe jabo. .parents[] ei bracket e sei no.ta likhbo. 

data_dir=proj_dir/"data"# ekhane amar data proj_dir er undere datar modhee ase . path ta dite hobe
files= os.listdir(data_dir)

import pandas as pd
datasets={}
for file_name in files:
  datasets[file_name] = pd.read_csv(data_dir/file_name)
  #tahole ami data gulo dekhte parbo
  

In [4]:
datasets["sample_10_2d.csv"]

1
0      1
1      1
2      1
3      1
4      1
...   ..
14336  0
14337  0
14338  0
14339  0
14340  0

[14341 rows x 1 columns]

In [20]:
datasets[10]

1
0     1
1     1
2     1
3     0
4     1
...  ..
4994  1
4995  0
4996  1
4997  1
4998  1

[4999 rows x 1 columns]

In [4]:
#import pandas as pd
#obs_ts=pd.read_csv("C:/Users/arumana/OneDrive - Viewpoint Capital Corporation/Documents/sample_1_2d.csv")
#obs_ts

1
0   1
1   1
2   1
3   0
4   1
.. ..
94  1
95  0
96  0
97  0
98  0

[99 rows x 1 columns]

In [4]:
# Initialize infer object
analyzer = infer.MarkovInfer(2, 2)

In [5]:
# Now we can use initial 'guesses' for A and B to pass into the optimizer
A_init = np.array([
    [0.75, 0.3],
    [0.25, 0.7]
])

B_init = np.array([
    [0.95, 0.10],
    [0.05, 0.90]
])


In [6]:
# Now to run the optimization, we can call like this (these are all using
# default arguments, so you dont actually need to include the symmetric or
# opt_type arguments here)
#result_local = analyzer.optimize(obs_ts.to_numpy().reshape(-1), A_init, B_init, symmetric=False, opt_type=OptClass.Local)
#onek time e datar shape dilh thakena, tokhon amra ebahbe kori
result_local_1 = analyzer.optimize(datasets[1], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_2 = analyzer.optimize(datasets[2], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_4 = analyzer.optimize(datasets[4], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_6 = analyzer.optimize(datasets[6], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_8 = analyzer.optimize(datasets[8], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_10 = analyzer.optimize(datasets[10], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_12 = analyzer.optimize(datasets[12], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_14 = analyzer.optimize(datasets[14], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_15 = analyzer.optimize(datasets[15], A_init, B_init, symmetric=False, opt_type=OptClass.Local)
result_local_16 = analyzer.optimize(datasets[16], A_init, B_init, symmetric=False, opt_type=OptClass.Local)


In [29]:
# For a global optimization (using SHGO algorithm)
result_global_1 = analyzer.optimize(datasets[1], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_2 = analyzer.optimize(datasets[2], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_4 = analyzer.optimize(datasets[4], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_6 = analyzer.optimize(datasets[6], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_8 = analyzer.optimize(datasets[8], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_10 = analyzer.optimize(datasets[10], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_12 = analyzer.optimize(datasets[12], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_14 = analyzer.optimize(datasets[14], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_15 = analyzer.optimize(datasets[15], A_init, B_init, symmetric=False, opt_type=OptClass.Global)
result_global_16 = analyzer.optimize(datasets[16], A_init, B_init, symmetric=False, opt_type=OptClass.Global)

c:\Users\arumana\Anaconda3\envs\hid\lib\site-packages\scipy\optimize\_optimize.py:353: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


In [27]:
# ANd then if you wanted a symmetric model
A_init_sym = np.array([
    [0.75, 0.25],
    [0.25, 0.75]
])

B_init_sym = np.array([
    [0.90, 0.10],
    [0.10, 0.90]
])

result_local_sym = analyzer.optimize(datasets[1], A_init_sym, B_init_sym, symmetric=True)

In [28]:
result_local_1.A, result_local_1.B,result_local_2.A, result_local_2.B,result_local_4.A, result_local_4.B,result_local_6.A, result_local_6.B,result_local_8.A, result_local_8.B,result_local_10.A, result_local_10.B,result_local_12.A, result_local_12.B,result_local_14.A, result_local_14.B,result_local_15.A, result_local_15.B,result_local_16.A, result_local_16.B

(array([[0.98007302, 0.01429649],
        [0.01992698, 0.98570351]]),
 array([[0.9947403 , 0.00616637],
        [0.0052597 , 0.99383363]]),
 array([[0.87511295, 0.10166687],
        [0.12488705, 0.89833313]]),
 array([[0.75036377, 0.13393873],
        [0.24963623, 0.86606127]]),
 array([[0.85117483, 0.13605374],
        [0.14882517, 0.86394626]]),
 array([[0.89765155, 0.10866914],
        [0.10234845, 0.89133086]]),
 array([[0.82670526, 0.1821382 ],
        [0.17329474, 0.8178618 ]]),
 array([[0.88366842, 0.0936138 ],
        [0.11633158, 0.9063862 ]]),
 array([[0.82633106, 0.19804347],
        [0.17366894, 0.80195653]]),
 array([[0.87813982, 0.08652946],
        [0.12186018, 0.91347054]]),
 array([[0.79287478, 0.2274655 ],
        [0.20712522, 0.7725345 ]]),
 array([[0.89283633, 0.06115281],
        [0.10716367, 0.93884719]]),
 array([[0.82601803, 0.21075549],
        [0.17398197, 0.78924451]]),
 array([[0.9629796, 0.1136678],
        [0.0370204, 0.8863322]]),
 array([[0.76095633, 0.3

In [27]:
hmm.A, hmm.B

(array([[0.8, 0.2],
        [0.2, 0.8]]),
 array([[0.9, 0.1],
        [0.1, 0.9]]))

In [31]:
result_global_1.A, result_global_1.B,result_global_2.A, result_global_2.B,result_global_4.A, result_global_4.B,result_global_6.A, result_global_6.B,result_global_8.A, result_global_8.B,result_global_10.A, result_global_10.B,result_global_12.A, result_global_12.B,result_global_14.A, result_global_14.B,result_global_15.A, result_global_15.B,result_global_16.A, result_global_16.B

(array([[0.98007322, 0.01429634],
        [0.01992678, 0.98570366]]),
 array([[0.99474068, 0.00616658],
        [0.00525932, 0.99383342]]),
 array([[0.87511419, 0.1016661 ],
        [0.12488581, 0.8983339 ]]),
 array([[0.75036245, 0.13393872],
        [0.24963755, 0.86606128]]),
 array([[0.86394656, 0.14882555],
        [0.13605344, 0.85117445]]),
 array([[0.10867  , 0.8976515],
        [0.89133  , 0.1023485]]),
 array([[0.82670521, 0.18213832],
        [0.17329479, 0.81786168]]),
 array([[0.88366837, 0.0936137 ],
        [0.11633163, 0.9063863 ]]),
 array([[0.82633124, 0.19804399],
        [0.17366876, 0.80195601]]),
 array([[0.87813918, 0.08652716],
        [0.12186082, 0.91347284]]),
 array([[0.77253427, 0.20712528],
        [0.22746573, 0.79287472]]),
 array([[0.06115286, 0.89283606],
        [0.93884714, 0.10716394]]),
 array([[0.78924536, 0.17397997],
        [0.21075464, 0.82602003]]),
 array([[0.1136677 , 0.96297797],
        [0.8863323 , 0.03702203]]),
 array([[0.7609567 , 0.3

In [32]:
result_local_sym.A, result_local_sym.B

(array([[0.98336039, 0.01663961],
        [0.01663961, 0.98336039]]),
 array([[0.9942074, 0.0057926],
        [0.0057926, 0.9942074]]))

3 state HMM

In [1]:
import os
import numpy as np
from hidden import dynamics, infer
# This is only if you want to use non-default optimization routines (global)
from hidden.optimize.base import OptClass

# Initializedynamics
hmm3=dynamics.HMM(3,3) 
hmm3.init_uniform_cycle(0.2, 0.1) 
hmm3.A, hmm3.B

(array([[0.6, 0.2, 0.2],
        [0.2, 0.6, 0.2],
        [0.2, 0.2, 0.6]]),
 array([[0.8, 0.1, 0.1],
        [0.1, 0.8, 0.1],
        [0.1, 0.1, 0.8]]))

In [2]:
hmm3.run_dynamics(250)

In [3]:
#eta diye data automatic save kora jae.
import os
from pathlib import Path
proj_dir= Path().resolve().parents[1]
#proj_dir= Path().resolve().parents[] first e eta diye dekhbo amra koi asi, ekhane amar data ta hmm er under e . first path 

#theke amar hmm path porjonto koto tuku 0,1,ebhabe jabo. .parents[] ei bracket e sei no.ta likhbo. 

data_dir=proj_dir/"data"# ekhane amar data proj_dir er undere datar modhee ase . path ta dite hobe
files= os.listdir(data_dir)

import pandas as pd
datasets=[]
for file_name in files:
  datasets.append(pd.read_csv(data_dir/file_name))
  #tahole ami data gulo dekhte parbo
  

In [4]:
# Initialize infer object
analyzer = infer.MarkovInfer(3, 3)

In [5]:
# Now we can use initial 'guesses' for A and B to pass into the optimizer
A3_init = np.array([
    [0.70, 0.2,0.75],
    [0.20, 0.7,0.15],
    [0.10,0.1,0.1]
])

B3_init = np.array([
    [0.85, 0.10,0.70],
    [0.05, 0.80,0.20],
    [0.10,0.10,0.10]
])


In [48]:
result_local_3 = analyzer.optimize(datasets[3], A3_init, B3_init, symmetric=False, opt_type=OptClass.Local)
result_local_5 = analyzer.optimize(datasets[5], A3_init, B3_init, symmetric=False, opt_type=OptClass.Local)
result_local_7 = analyzer.optimize(datasets[7], A3_init, B3_init, symmetric=False, opt_type=OptClass.Local)
result_local_9 = analyzer.optimize(datasets[9], A3_init, B3_init, symmetric=False, opt_type=OptClass.Local)
result_local_11 = analyzer.optimize(datasets[11], A3_init, B3_init, symmetric=False, opt_type=OptClass.Local)
result_local_13 = analyzer.optimize(datasets[13], A3_init, B3_init, symmetric=False, opt_type=OptClass.Local)

In [50]:
result_local_3.A,result_local_3.B,result_local_5.A,result_local_5.B,result_local_7.A,result_local_7.B,result_local_9.A,result_local_9.B,result_local_11.A,result_local_11.B,result_local_13.A,result_local_13.B,


(array([[0.7 , 0.2 , 0.75],
        [0.2 , 0.7 , 0.15],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.85, 0.1 , 0.7 ],
        [0.05, 0.8 , 0.2 ],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.7 , 0.2 , 0.75],
        [0.2 , 0.7 , 0.15],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.85, 0.1 , 0.7 ],
        [0.05, 0.8 , 0.2 ],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.7 , 0.2 , 0.75],
        [0.2 , 0.7 , 0.15],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.85, 0.1 , 0.7 ],
        [0.05, 0.8 , 0.2 ],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.7 , 0.2 , 0.75],
        [0.2 , 0.7 , 0.15],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.85, 0.1 , 0.7 ],
        [0.05, 0.8 , 0.2 ],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.7 , 0.2 , 0.75],
        [0.2 , 0.7 , 0.15],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.85, 0.1 , 0.7 ],
        [0.05, 0.8 , 0.2 ],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.7 , 0.2 , 0.75],
        [0.2 , 0.7 , 0.15],
        [0.1 , 0.1 , 0.1 ]]),
 array([[0.85, 0.1 , 0.7 ],
        [0.05, 0.8 , 0.2 ]

In [7]:
hmm3.A,hmm3.B

(array([[0.6, 0.2, 0.2],
        [0.2, 0.6, 0.2],
        [0.2, 0.2, 0.6]]),
 array([[0.8, 0.1, 0.1],
        [0.1, 0.8, 0.1],
        [0.1, 0.1, 0.8]]))

In [6]:
result_global_3 = analyzer.optimize(datasets[3], A3_init, B3_init, symmetric=False, opt_type=OptClass.Global)
result_global_5 = analyzer.optimize(datasets[5], A3_init, B3_init, symmetric=False, opt_type=OptClass.Global)
#result_global_7 = analyzer.optimize(datasets[7], A3_init, B3_init, symmetric=False, opt_type=OptClass.Global)
#result_global_9 = analyzer.optimize(datasets[9], A3_init, B3_init, symmetric=False, opt_type=OptClass.Global)
#result_global_11= analyzer.optimize(datasets[11], A3_init, B3_init, symmetric=False, opt_type=OptClass.Global)
#result_global_13 = analyzer.optimize(datasets[13], A3_init, B3_init, symmetric=False, opt_type=OptClass.Global)